### ISSUE TITLE
[BUG] Package is not in npm registry

### ISSUE THREAD

**Issue by daffron** [npm/run-script#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Within the last 2 hours, the package seems to have disappeared from the registry, or been made private. As cannot access via the browser either:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@npmcli%2frun-script - Not found
npm ERR! 404 
npm ERR! 404  '@npmcli/run-script@4.2.1' is not in this registry.
```

### Expected Behavior

To be available 

### Steps To Reproduce

1. Try install this package

### Environment

- npm: 8.11.0
- Node: 18.3.0
- OS: PopOS 20.04
- platform: Local and in CI (Github)

**Comment by fdescaves** [comment]
Currently experiencing the same issue, it seems to have been made private by the owner.

**Comment by raschan** [comment]
It might be related to the currently ongoing authentication issue with [npmjs](https://status.npmjs.org/)

**Comment by daffron** [comment]
Agreed- now facing the issue with another package so will close this issue
