### ISSUE TITLE
[BUG] npm run-scripts fail in windows 10 with case-sensitivity enabled.

### ISSUE THREAD

**Issue by gliesefire** [npm/run-script#29]
# What / Why

> After Windows 10’s April 2018 Update, directories can be set as [case-sensitive](https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/)
So being a case-sensitive directory, you cannot execute batch files ( or any executable in general) by skipping the extensions
Thus while specifying the npm package executable inside **scripts**,  .cmd should be explicitly specified, otherwise it doesn't work.
But if I specify it explicitly, the package no longer works cross-platform.

### Current Behavior

* Since there already exists an 'extension-less' browserslist file, the spawn process passes that to cmd.exe, and that in turn doesn't recognize that as an windows executable, almost as if the file doesn't exist. *start* command explicitly outputs that error.
```
> client_app@1.0.0 build
> browserslist --version

'browserslist' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to Reproduce

* Create a directory, set it as case-sensitive using the command `fsutil.exe file setCaseSensitiveInfo <path> enable`
* Create a package config which has dependencies to any npm package with install script, e.g. browserslist
```json
{
  "name": "client_app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "demo": "browserslist --version"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "browserslist": "^4.16.5"
  }
}
```
* npm run demo

### Expected Behavior

* It should print the version of browserslist
```
> client_app@1.0.0 build
> browserslist.cmd --version

browserslist 4.16.5
```

If this is recognized as package issue instead of an OS issue, then I can attempt to make necessary changes to make-spawn-args file to fix this.

**Comment by vweevers** [comment]
> So being a case-sensitive directory, you cannot execute batch files ( or any executable in general) by skipping the extensions

For those wondering why: the default value of `PATHEXT` (an environment variable used to match extensionless commands to filenames) is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC` (note the casing). After enabling case sensitivity, one must `set PATHEXT=%PATHEXT%;.cmd` for `browserslist.cmd` to be found when running the command `browserslists`.

**Comment by gliesefire** [comment]
Wow, that worked. Thanks for the info 👍🏼.
I will close this
