### ISSUE TITLE
Update node-gyp to avoid npm install warnings

### ISSUE THREAD

**Issue by apepper** [npm/run-script#33]
If you install `@npmcli/run-script` in an empty folder npm will warn about three deprecated libraries:

```
> npm i @npmcli/run-script
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

This is because of:

https://github.com/npm/run-script/blob/47a4d539fb07220e7215cc0e482683b76407ef9b/package.json#L34

AFAICS if one would update `node-gyp` to version 8 all these warnings would go away, since `node-gyp` no longer uses `request`, which uses `har-validator` and `uuid` as sup-dependencies.

See https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v800-2021-04-03 for the changelog of `node-gyp` version 8.

**Comment by wraithgar** [comment]
We can't move to this version of node-gyp in npm@7. See this PR for more info https://github.com/npm/run-script/pull/32
