### ISSUE TITLE
[BUG] Migrate to `node-gyp@^8`

### ISSUE THREAD

**Issue by stramel** [npm/run-script#35]
# What / Why

> Migrating to `node-gyp` v8 would remove the package `request` which has multiple warnings related to it.
> Related PR https://github.com/nodejs/node-gyp/pull/2220

- a warning about usage of older `Math.random()`
> `npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`
- a warning about no longer maintained package `har-validator` usage
> `npm WARN deprecated har-validator@5.1.5: this library is no longer supported`
- a warning about the package itself (`request`) being deprecated
> `npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by wraithgar** [comment]
We can't move to this version of node-gyp in npm@7. See this PR for more info https://github.com/npm/run-script/pull/32

**Comment by stramel** [comment]
@wraithgar Ah, sorry about that. Thank you for the link to more information behind the decision!
