### ISSUE TITLE
[?BUG] package.json -> process.env - Array is smashed, while object can be deep

### ISSUE THREAD

**Issue by askirmas** [npm/run-script#37]
What is the purpose of this decision?
https://github.com/npm/run-script/blob/7e7b52a3dbfd5ea7870217a290403ce6757627e6/test/package-envs.js#L29-L30
https://github.com/npm/run-script/blob/7e7b52a3dbfd5ea7870217a290403ce6757627e6/lib/package-envs.js#L11-L14
Related: https://github.com/npm/cli/issues/3775

**Comment by lukekarrys** [comment]
Fixed by #194
