### ISSUE TITLE
[BUG] v3.0.1 has a breaking change

### ISSUE THREAD

**Issue by ljharb** [npm/run-script#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

v3.0.1 includes node-gyp 9 in #52, but this was a breaking change, because node-gyp 9 requires node 12.22, and run-script v3.0.0 only require node v12.13.

Can that update be reverted in a v3.0.3?

**Comment by lukekarrys** [comment]
Closed by #73
